[package]
name = "http-manager"
version = "0.0.1" # https://crates.io/crates/http-manager/versions
edition = "2021"
rust-version = "1.62"
publish = true
description = "HTTP manager"
homepage = "https://github.com/gyuho/http-manager"
license = "Apache-2.0"

[dependencies]
hyper = { version = "0.14.19", features = ["full"], optional = false }
hyper-tls = { version = "0.5.0", optional = false }
log = "0.4.17"
reqwest = { version = "0.11.11", optional = false }
tokio = { version = "1.19.2", features = ["full"], optional = false } # ref. https://github.com/tokio-rs/tokio/releases
url = { version = "2.2.2", optional = false }

[dev-dependencies]
env_logger = "0.9.0"
tokio-test = "0.4.2"
